### ISSUE TITLE
Pagination/Archive for materialdesignicons.com/history

### ISSUE THREAD

**Issue by rexyiy** [Templarian/MaterialDesign-Site#44]
Hi,
i hope this is the right place for this feature request:
I really like to check the page materialdesignicons.com/history often to find new icons. But the page is getting bigger and bigger and takes lots of time to load (and sometimes crashes my tab in the browser).
pagination would be a good solution. As an easier alternative there could be one archive page with all the icons and the history page with only the last maybe 6 or 12 months (or the last 100 changes, if that is easier).
Regards,
Rex

**Comment by Templarian** [comment]
http://dev.materialdesignicons.com/history Is already done.

Need to remove alias from the legacy endpoints so that old page at least loads on the current site.

// edit to clarify, this repo is for the new site, but will keep this issue opened for me to track the legacy endpoint update to ignore aliases and only return the last ~200 items.

**Comment by Templarian** [comment]
I limited it to 500 items and added a note that the list is current truncated.

It links to the dev server also if they need to view all entries. The individual icon pages will have their own history entries also. This should make it easier to track changes.
