### ISSUE TITLE
Ability to access public API

### ISSUE THREAD

**Issue by EdricChan03** [Templarian/MaterialDesign-Site#47]
When trying to access a specific API (such as the Icon API), I keep getting this error:

```
Failed to load http://dev.materialdesignicons.com/api/icon/CD5DD59A-965F-455E-912B-9535BFD134E0: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

Could the header on the resource be set as such? And also make the site be SSL-encrypted so that requests from another SSL-encrypted website will not be blocked by the browser.

Thanks.

**Comment by Templarian** [comment]
@Chan4077 Sorry, the API is not for external apps. That API is only for this open source website.

All the site's data is in https://github.com/Templarian/MaterialDesign-SVG

Look at the `meta.json` file. You can use the `svg/` + `meta.json` to produce tools.

**Comment by jacobq** [comment]
@Chan4077 as Austin noted, this API is not to be used other than for the MDI site. However, you may find [cors-anywhere](https://github.com/Rob--W/cors-anywhere) (e.g. `curl -i -H 'Origin: http://example.com' https://cors-anywhere.herokuapp.com/http://dev.materialdesignicons.com/api/icon/CD5DD59A-965F-455E-912B-9535BFD134E0`) and [Fiddler](https://www.telerik.com/fiddler) are useful tools for local development and testing of requests that would otherwise fail due to CORS.
